from __future__ import annotations

import csv
from collections.abc import Iterable
from dataclasses import dataclass
from importlib.resources import files

from tickbiterisk.etl.maryland import maryland_fips_set
from tickbiterisk.etl.weather_config import REGIONAL_STATES

# Canonical six-state weather locations resource (generated by
# scripts/build_weather_locations_resource.py from the regional county set).
WEATHER_LOCATIONS_RESOURCE = "weather_locations.csv"


class WeatherLocationError(ValueError):
    """Raised when weather location loading or state selection is invalid."""


@dataclass(frozen=True)
class WeatherLocation:
    county_fips: str
    state_fips: str
    state: str
    county_name: str
    centroid_lat: float
    centroid_lon: float
    geography_source: str


def load_maryland_weather_locations() -> list[WeatherLocation]:
    resource = files("tickbiterisk.resources").joinpath(
        "maryland_weather_locations.csv"
    )
    with resource.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))

    locations = [
        WeatherLocation(
            county_fips=str(row["county_fips"]).zfill(5),
            state_fips=str(row["state_fips"]).zfill(2),
            state=row["state"],
            county_name=row["county_name"],
            centroid_lat=float(row["centroid_lat"]),
            centroid_lon=float(row["centroid_lon"]),
            geography_source=row["geography_source"],
        )
        for row in rows
    ]

    fips = {row.county_fips for row in locations}
    expected = maryland_fips_set()
    if len(locations) != 24 or fips != expected:
        missing = sorted(expected - fips)
        extra = sorted(fips - expected)
        raise ValueError(
            "Weather location resource must match Maryland jurisdictions; "
            f"missing={missing}, extra={extra}, count={len(locations)}"
        )
    return locations


def _read_weather_location_rows() -> list[WeatherLocation]:
    resource = files("tickbiterisk.resources").joinpath(WEATHER_LOCATIONS_RESOURCE)
    with resource.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    return [
        WeatherLocation(
            county_fips=str(row["county_fips"]).zfill(5),
            state_fips=str(row["state_fips"]).zfill(2),
            state=row["state"],
            county_name=row["county_name"],
            centroid_lat=float(row["centroid_lat"]),
            centroid_lon=float(row["centroid_lon"]),
            geography_source=row["geography_source"],
        )
        for row in rows
    ]


def load_weather_locations(
    states: Iterable[str] | None = None,
) -> list[WeatherLocation]:
    """Load weather county locations for the six-state regional product.

    Generalizes the Maryland-only loader: any subset of the six regional
    jurisdictions (DE, DC, MD, PA, VA, WV) can be requested via ``states``;
    omitting it returns all six. Fails loud on a non-regional state or a
    requested state with no counties in the resource (rather than silently
    returning an empty series that would break a downstream fit).
    """
    locations = _read_weather_location_rows()

    if states is None:
        selected_states = list(REGIONAL_STATES)
    else:
        selected_states = [str(state).strip().upper() for state in states]
        if not selected_states:
            raise WeatherLocationError("states must name at least one jurisdiction")
        unknown = [s for s in selected_states if s not in REGIONAL_STATES]
        if unknown:
            raise WeatherLocationError(
                f"non-regional jurisdiction(s) requested: {unknown}; "
                f"allowed: {list(REGIONAL_STATES)}"
            )

    wanted = set(selected_states)
    filtered = [row for row in locations if row.state in wanted]

    present_states = {row.state for row in filtered}
    missing_states = sorted(wanted - present_states)
    if missing_states:
        raise WeatherLocationError(
            f"weather locations resource has no counties for requested state(s): "
            f"{missing_states}"
        )

    seen_fips: set[str] = set()
    for row in filtered:
        if len(row.county_fips) != 5:
            raise WeatherLocationError(
                f"invalid county_fips in weather locations resource: {row.county_fips}"
            )
        if row.county_fips in seen_fips:
            raise WeatherLocationError(
                f"duplicate county_fips in weather locations resource: {row.county_fips}"
            )
        seen_fips.add(row.county_fips)

    return sorted(filtered, key=lambda row: row.county_fips)
